<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Créér un utilisateur</title>
</head>
<body>
    <h1>Créér un utilisateur</h1>
    <main>
        <form action="./index.php?route=check_create_user" method="POST">
                <fieldset>
                    <label for="first_name" class="form-label">Prénom</label>
                    <input type="text" id="first_name" name="first_name" class="form-control" />
                </fieldset>
                <fieldset>
                    <label for="last_name" class="form-label">Nom</label>
                    <input type="text" id="last_name" name="last_name" class="form-control" />
                </fieldset>
                <fieldset>
                    <label for="email" class="form-label">Email</label>
                    <input type="email" id="email" name="email" class="form-control" />
                </fieldset>
                <button type="submit" class="mt-3 btn btn-primary">Sauvegarder</button>
            </form>
    </main>
</body>
</html>