<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Utilisateurs</title>
    <link rel="stylesheet" href="../assets/styles/style.css">
    <link rel="stylesheet" href="../assets/styles/style.scss">
</head>
<body>
    <header>
        <h1>Utilisateurs</h1>
        <nav>
            <ul>
                <li><a href="./index.php">Accueil</a></li>
                <li><a href="index.php?route=users/create.phtml">Créér un utilisateur</a></li>
                <li><a href="index.php?route=users/update.phtml">Mettre à jour un utilisateur</a></li>
                <li><a href="index.php?route=users/list.phtml">Liste des utilisateurs</a></li>
                <li><a href="index.php?route=users/show.phtml">Voir un utilisateur</a></li>
            </ul>
        </nav>
    </header>
    <main>
       <?php
			if (isset($route)) {
				require "templates/users/$route.phtml";
			}
		?>
    </main>
    <script type="text/javascript" href="../assets/js/script.js">  </script>
</body>
</html>