

<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title>Création d'un utilisateur</title>
    </head>
    <body class="container-fluid">
        <main class="p-5">
            <form class="col mt-5" action="../index.php?route=check_create_user" method="POST">
                <fieldset>
                    <label for="first_name" class="form-label">Prénom</label>
                    <input type="text" id="first_name" name="first_name" class="form-control" />
                </fieldset>
                <fieldset>
                    <label for="last_name" class="form-label">Nom</label>
                    <input type="text" id="last_name" name="last_name" class="form-control" />
                </fieldset>
                <fieldset>
                    <label for="email" class="form-label">Email</label>
                    <input type="email" id="email" name="email" class="form-control" />
                </fieldset>
                <button type="submit" class="mt-3 btn btn-primary">Sauvegarder</button>
            </form>
        </main>
    </body>
</html>
            

            